name: Pipeline Templates CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: [main]

jobs:
  traffic-light-pipeline:
    uses: ./.github/workflows/traffic-light-pipeline.yml
    with:
      ci-tool: 'gh_actions'
      default-cloud-provider: 'aws'
    secrets:
      terraform-cloud-token: ${{ secrets.TF_CLOUD_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
      civo-token: ${{ secrets.CIVO_TOKEN }}
      oci-tenancy-ocid: ${{ secrets.OCI_TENANCY_OCID }}
      oci-user-ocid: ${{ secrets.OCI_USER_OCID }}
      oci-fingerprint: ${{ secrets.OCI_FINGERPRINT }}
      oci-private-key: ${{ secrets.OCI_PRIVATE_KEY }}
      oci-region: ${{ secrets.OCI_REGION }}
      oci-compartment-id: ${{ secrets.OCI_COMPARTMENT_ID }}